[tool.bump-my-version]
current_version = "0.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true

[tool.bump-my-version.file_patterns]
"pyproject.toml" = [
    'current_version = "{current_version}"',
    'version = "{current_version}"'
]
"src/seekwellpandas/__init__.py" = [
    '__version__ = "{current_version}"'
]
"docs/source/conf.py" = [
    'release = "{current_version}"'
]