[tool.bump-my-version]
current_version = "0.2"  # Assurez-vous que cette version correspond à votre version actuelle
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version: {current_version} → {new_version}"
tag_message = "{new_version}"
tag = true
sign_tags = false

[[tool.bump-my-version.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bump-my-version.files]]
filename = "seekwellpandas/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

# Ajoutez d'autres fichiers si nécessaire