name: Build and Deploy Sphinx Documentation
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme nbsphinx
        pip install .
        pip freeze
        sudo apt-get install pandoc
    - name: Build Documentation
      run: |
        cd docs
        make html
        echo "Contents of _build/html directory:"
        ls -R _build/html
      continue-on-error: true
    - name: Check build output
      run: |
        ls -R docs/_build/html
    - name: Clean Actions cache
      run: |
        rm -rf $GITHUB_WORKSPACE/.github/workflows/.cache
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html