name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme nbsphinx
        pip install .
        pip freeze

    - name: Debug environment
      run: |
        pwd
        ls -R
        python -c "import pandalchemy; print(pandalchemy.__file__)"
        python -c "from pandalchemy import methods; print(methods.__file__)"

    - name: Build Documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html -v  # Verbose output

    - name: Check build output
      run: |
        ls -R docs/_build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html